### ISSUE TITLE
Be able to forward parameter to wsdd.py and samba.sh

### ISSUE THREAD

**Issue by Nobody84** [Nobody84/docker-samba#2]
Currently it's only pissible to forward parameter to the samba.sh but not to the wsd.py.
There should be a possibility to forward parameter to the wsdd.py too.

**Comment by DavidAUM23** [comment]
Thanks for working on this.
One thing I noticed was the use of "wssd" instead of "wsdd" in the documentation.
I didn't inspect further to see if that typo traveled into the code.

But for me, when I run this, it appears to be passing the arguments as expect, but the container just keeps restarting.

Here is the whole of what I am running:
```
sudo docker run -it \
--name smb_wsdd \
-p 137-138:137-138/udp \
-p 139:139 -p 445:445 \
-v /shares/share1:/share1 \
-e SAMBA_PARAMETER="-p -s \"public;/share1\"" \
-e WSSD_PARAMETER="-i enp0s25" \
--restart unless-stopped \
-d topdockercat/samba
```

It appears to start fine, but then `docker ps` shows the container repeatedly restarting. 

Here is the log:
```
Start Web Service Discovery host daemon (WSDD)
Parameter: -i enp0s25

Start /usr/bin/samba.sh from original docker image
Parameter: -p -s "public;/share1"
Start Web Service Discovery host daemon (WSDD)
Parameter: -i enp0s25

Start /usr/bin/samba.sh from original docker image
Parameter: -p -s "public;/share1"
Start Web Service Discovery host daemon (WSDD)
Parameter: -i enp0s25

Start /usr/bin/samba.sh from original docker image
...
```

Also, if I pass the Samba args as commandline parameters, I need to escape the double-quotes and semicolon to get the log to report the same as above.

If I send 
```
topdockercat/samba
-p \
-s "public;/share1"
```
It yields logs:
```
Start Web Service Discovery host daemon (WSDD)
Parameter: -i enp0s25

Start /usr/bin/samba.sh from original docker image
Parameter: -p -s public;/share1
```
With no double-quotes around the share info.

Matches the log output of using the environment variable if I escape it thusly `-s \"public\;/share1\"`

But in either case, the container just goes into a restart loop.

**Comment by DavidAUM23** [comment]
A couple more little typos using wssd in headings that flow to their links :
https://github.com/Nobody84/docker-samba#configure-wssd-andor-samba
https://github.com/Nobody84/docker-samba#wssd

**Comment by Nobody84** [comment]
Hopefully all typos fixed.
